import { eq } from "drizzle-orm";
import { db } from "../db";
import { batches, sessions, turns } from "../db/schema";

type ModelConfig = {
  providerId: string;
  modelId: string;
};

const autoGeneratedName = () => {
  const adjectives = [
    "Amazing",
    "Awesome",
    "Fantastic",
    "Incredible",
    "Super",
    "Wonderful",
    "Brilliant",
    "Exceptional",
    "Outstanding",
    "Marvelous",
  ];
  const nouns = ["comparison", "run", "test"];
  return `${adjectives[Math.floor(Math.random() * adjectives.length)]} ${
    nouns[Math.floor(Math.random() * nouns.length)]
  }`;
};

export const createSession = async (
  providerId: string,
  modelId: string,
  batchId: number,
  opencodeSessionId: string,
  directory: string,
) => {
  const [session] = await db
    .insert(sessions)
    .values({
      providerId,
      modelId,
      batchId,
      opencodeSessionId,
      directory,
    })
    .returning();
  if (!session) {
    throw new Error("Failed to create session");
  }
  return session;
};

export const createTurn = async (sessionId: number, currentTime: Date) => {
  const [turn] = await db
    .insert(turns)
    .values({
      sessionId,
      startTime: currentTime,
    })
    .returning();
  if (!turn) {
    throw new Error("Failed to create turn");
  }
  return turn;
};

const getTurn = async (sessionId: number) => {
  const [turn] = await db
    .select()
    .from(turns)
    .where(eq(turns.sessionId, sessionId))
    .limit(1);
  if (!turn) {
    throw new Error("Turn not found");
  }
  return turn;
};

// for now, we're having single turns, on multi-turn support, update accordingly
export const updateSingularTurn = async (
  sessionId: number,
  status: "pending" | "completed" | "failed",
  error?: string,
  endTime?: Date,
) => {
  const [turn] = await db
    .update(turns)
    .set({
      status,
      error,
      endTime,
    })
    .where(eq(turns.sessionId, sessionId))
    .returning();
  if (!turn) {
    throw new Error("Failed to update turn");
  }
  return turn;
};

export const createBatch = async (modelConfigs: ModelConfig[]) => {
  const name = autoGeneratedName();
  const [batch] = await db.insert(batches).values({ name }).returning();
  if (!batch) {
    throw new Error("Failed to create batch");
  }

  return batch.id;
};
